/**
 * Questions du quiz "La Boîte à Merveilles", organisées chapitre par
 * chapitre — demandé explicitement par l'utilisateur, en deux temps :
 * "tu peux le quiz tu le fais chap par chap faire 5 qst dans chaque
 * chapter" puis "15 qst dans chaque chapter". 15 questions par
 * chapitre (1 à 12), 180 au total.
 *
 * ⚠️ Contenu entièrement rédigé par Claude, à partir des résumés et
 * points clés déjà en base (table `fiches`, remplis les sessions
 * précédentes à partir des points fournis par l'utilisateur) — chaque
 * question est vérifiable dans le résumé du chapitre correspondant
 * (relu directement depuis Supabase avant rédaction, pour ancrer
 * chaque question/réponse dans le contenu réel plutôt que dans un
 * souvenir approximatif du roman), mais la formulation des
 * questions/réponses elle-même n'a pas été fournie par l'utilisateur :
 * à faire relire par un enseignant avant usage en classe (même réserve
 * que le lexique/les sujets, qui n'ont pas non plus de colonne
 * `statut`).
 *
 * Stocké en dur ici plutôt qu'en base : un vrai quiz demanderait une
 * nouvelle table Supabase (questions/choix/bonne réponse), donc une
 * migration, impossible à appliquer directement dans ce projet (pas de
 * connexion Postgres, seulement les clés REST anon/service_role). Même
 * contournement que `lib/personnagesParChapitre.ts`.
 */
export interface QuestionQuiz {
  id: string;
  question: string;
  choix: string[];
  /** Index dans `choix` de la bonne réponse. */
  reponseCorrecte: number;
  /** Courte explication affichée après la réponse, pour justifier la
   * bonne réponse (pédagogique, pas juste "correct/incorrect"). */
  explication: string;
}

export const QUIZ_PAR_CHAPITRE: Record<number, QuestionQuiz[]> = {
  1: [
    {
      id: "c1-q1",
      question: "Pourquoi la maison où vit le narrateur s'appelle-t-elle « Dar Chouafa » ?",
      choix: [
        "Parce qu'elle appartient à une riche famille de ce nom",
        "Parce qu'une voyante habite au rez-de-chaussée et y organise un rituel mensuel",
        "Parce qu'elle est voisine du Msid",
        "Parce que son propriétaire s'appelle Chouafa",
      ],
      reponseCorrecte: 1,
      explication:
        "La Chouafa (tante Kenza), voyante, occupe le rez-de-chaussée et y organise chaque mois un rituel qui trouble l'enfant.",
    },
    {
      id: "c1-q2",
      question: "En quoi le narrateur enfant se distingue-t-il des autres écoliers du Msid ?",
      choix: [
        "Il est plus doué qu'eux en récitation",
        "Il refuse d'aller au Msid",
        "Il vit dans le rêve et l'imagination, quand eux restent tournés vers le réel",
        "Il est le plus âgé de la classe",
      ],
      reponseCorrecte: 2,
      explication:
        "Le narrateur oppose son goût pour le rêve et l'imaginaire au reste des écoliers, tournés vers le monde réel.",
    },
    {
      id: "c1-q3",
      question: "Comment l'enfant vit-il les séances au bain maure ?",
      choix: ["Comme un moment de jeu agréable", "Avec indifférence", "Comme une fête", "Comme un enfer qu'il redoute"],
      reponseCorrecte: 3,
      explication: "Le bain maure est décrit comme un véritable enfer que l'enfant redoute à chaque fois.",
    },
    {
      id: "c1-q4",
      question: "Qu'est-ce qui déclenche la dispute entre Lalla Zoubida et Rahma à la fin du chapitre ?",
      choix: [
        "Le partage de la boîte à merveilles",
        "Le jour de la lessive, le lundi",
        "Un vol d'argent",
        "Une histoire racontée par le fqih",
      ],
      reponseCorrecte: 1,
      explication: "La dispute porte sur le lundi, jour de lessive, avant de s'envenimer le soir même en bagarre.",
    },
    {
      id: "c1-q5",
      question: "Comment l'enfant réagit-il devant la violence de la bagarre qui referme le chapitre ?",
      choix: ["Il se met à crier", "Il va chercher son père", "Il s'évanouit", "Il se réfugie chez la voisine"],
      reponseCorrecte: 2,
      explication: "Incapable de supporter la violence de la scène, l'enfant s'évanouit.",
    },
    {
      id: "c1-q6",
      question: "Qui dirige le Msid, l'école coranique de ce chapitre ?",
      choix: ["Le fqih", "Driss El Aouad", "Abdellah l'épicier", "Maâlem Abdeslem"],
      reponseCorrecte: 0,
      explication:
        "Le fqih, homme maigre, barbu et sévère, dirige le Msid situé à la porte de Derb Noualla.",
    },
    {
      id: "c1-q7",
      question: "Comment le narrateur décrit-il la boîte à merveilles dans ce chapitre ?",
      choix: [
        "Comme un jouet parmi d'autres",
        "Comme son seul refuge et véritable compagnon",
        "Comme un cadeau récent de son père",
        "Comme un objet qu'il n'aime pas",
      ],
      reponseCorrecte: 1,
      explication: "Les objets qu'elle contient tiennent compagnie à l'enfant dans ses moments de solitude.",
    },
    {
      id: "c1-q8",
      question: "Comment le narrateur présente-t-il les locataires de Dar Chouafa ?",
      choix: [
        "Il les énumère tous en une seule phrase",
        "Il les découvre étage par étage, à travers le regard de l'enfant",
        "Il ne les mentionne pas",
        "Il les présente uniquement à la fin du chapitre",
      ],
      reponseCorrecte: 1,
      explication: "Le chapitre décrit la maison et ses habitants étage par étage, à hauteur d'enfant.",
    },
    {
      id: "c1-q9",
      question: "Devant qui la bagarre finale entre Lalla Zoubida et Rahma éclate-t-elle ?",
      choix: ["Devant les enfants seulement", "Devant les hommes", "Devant le fqih", "Devant la Chouafa"],
      reponseCorrecte: 1,
      explication: "La dispute dégénère en bagarre devant les hommes, ce que l'enfant ne supporte pas.",
    },
    {
      id: "c1-q10",
      question: "Sur quoi le narrateur adulte ouvre-t-il le récit, avant de remonter à son enfance ?",
      choix: ["Sur sa réussite professionnelle", "Sur sa solitude présente", "Sur son mariage", "Sur un voyage récent"],
      reponseCorrecte: 1,
      explication: "C'est en partant de sa solitude d'adulte qu'il remonte à ses souvenirs d'enfant.",
    },
    {
      id: "c1-q11",
      question: "Comment le fqih est-il décrit physiquement ?",
      choix: ["Jeune et souriant", "Maigre, barbu et sévère", "Corpulent et joyeux", "Aveugle"],
      reponseCorrecte: 1,
      explication: "Le fqih est présenté comme un homme maigre, barbu et sévère.",
    },
    {
      id: "c1-q12",
      question: "Qui, parmi ces personnages, habite Dar Chouafa avec le narrateur ?",
      choix: ["Le voyant Sidi El Arafi", "La Chouafa (tante Kenza)", "Salama la marieuse", "Abderrahman le coiffeur"],
      reponseCorrecte: 1,
      explication: "La Chouafa, la voyante, occupe le rez-de-chaussée de la maison qui porte son nom.",
    },
    {
      id: "c1-q13",
      question: "En plus de Dar Chouafa et du Msid, quel autre lieu est évoqué dans ce chapitre ?",
      choix: ["Le souk des bijoutiers", "Le bain maure", "Le sanctuaire de Sidi Ali Boughaleb", "La Kissaria"],
      reponseCorrecte: 1,
      explication: "Le bain maure, que l'enfant redoute comme un enfer, est l'un des lieux de ce premier chapitre.",
    },
    {
      id: "c1-q14",
      question: "Comment l'enfant vit-il, de façon générale, sa relation au monde réel dans ce chapitre ?",
      choix: [
        "Il s'y sent parfaitement à l'aise",
        "Il préfère le rêve et l'imagination à la réalité",
        "Il ne s'y intéresse pas du tout",
        "Il cherche à dominer les autres écoliers",
      ],
      reponseCorrecte: 1,
      explication: "Ce trait de caractère traverse tout le chapitre et annonce le rôle de la boîte à merveilles.",
    },
    {
      id: "c1-q15",
      question: "Où se situe précisément la maison de Dar Chouafa ?",
      choix: ["En plein centre du souk", "Au fond d'une impasse", "À côté du sanctuaire", "Sur la place du Msid"],
      reponseCorrecte: 1,
      explication: "Le narrateur précise que Dar Chouafa se trouve au fond d'une impasse.",
    },
  ],
  2: [
    {
      id: "c2-q1",
      question: "Pourquoi Lalla Zoubida se rend-elle au sanctuaire de Sidi Ali Boughaleb ?",
      choix: [
        "Pour assister à un mariage",
        "Conseillée par Lalla Aïcha, pour se délivrer de sa migraine et de ses malheurs",
        "Pour acheter des vêtements neufs",
        "Pour accompagner son mari en voyage",
      ],
      reponseCorrecte: 1,
      explication: "Terrassée par une migraine, elle suit le conseil de Lalla Aïcha de se rendre au mausolée.",
    },
    {
      id: "c2-q2",
      question: "Que subit Sidi Mohammed lors de la visite au mausolée ?",
      choix: ["Il se perd dans la foule", "Il se fait griffer par un chat", "Il tombe malade", "Il casse un objet sacré"],
      reponseCorrecte: 1,
      explication: "Le mausolée est infesté de chats, et l'enfant se fait griffer par un matou.",
    },
    {
      id: "c2-q3",
      question: "Combien de jours de repos la blessure du chat vaut-elle au narrateur ?",
      choix: ["Un jour", "Deux jours et demi", "Une semaine", "Aucun, il reste au Msid"],
      reponseCorrecte: 1,
      explication: "Sa blessure lui vaut deux jours et demi de repos à la maison.",
    },
    {
      id: "c2-q4",
      question: "Qui offre un cabochon de verre à Sidi Mohammed pendant sa convalescence ?",
      choix: ["Fatma Bziouya", "Lalla Aïcha", "Rahma", "La Chouafa"],
      reponseCorrecte: 2,
      explication: "Rahma lui offre un cabochon de verre, et Fatma Bziouya deux beignets.",
    },
    {
      id: "c2-q5",
      question: "Quel jour de la semaine le Msid consacre-t-il à la révision et à la récitation du Coran ?",
      choix: ["Le lundi", "Le mardi", "Le jeudi", "Le vendredi"],
      reponseCorrecte: 1,
      explication: "Le chapitre s'ouvre sur le souvenir du mardi, jour de révision et de récitation.",
    },
    {
      id: "c2-q6",
      question: "Qui vient rendre visite à Lalla Zoubida alors qu'elle souffre d'une violente migraine ?",
      choix: ["Fatma Bziouya", "Lalla Aïcha, son amie intime", "La Chouafa", "Rahma"],
      reponseCorrecte: 1,
      explication: "Lalla Aïcha, inquiète de la trouver si souffrante, lui conseille le pèlerinage.",
    },
    {
      id: "c2-q7",
      question: "Que conseille d'abord Lalla Aïcha à Lalla Zoubida, avant le pèlerinage ?",
      choix: ["Consulter un fqih", "Aller au souk", "Consulter un médecin", "Se reposer chez elle"],
      reponseCorrecte: 0,
      explication: "Lalla Aïcha lui conseille d'abord un fqih, puis le sanctuaire de Sidi Ali Boughaleb.",
    },
    {
      id: "c2-q8",
      question: "Qui accompagne Lalla Zoubida et Sidi Mohammed jusqu'au mausolée ?",
      choix: ["Fatma Bziouya", "Lalla Aïcha", "Rahma", "La Chouafa"],
      reponseCorrecte: 2,
      explication: "Rahma se joint à Lalla Zoubida et à son fils pour ce déplacement.",
    },
    {
      id: "c2-q9",
      question: "Que font les deux femmes en arrivant au sanctuaire ?",
      choix: [
        "Elles repartent aussitôt",
        "Elles se livrent à diverses pratiques superstitieuses",
        "Elles rencontrent le fqih",
        "Elles font des achats",
      ],
      reponseCorrecte: 1,
      explication: "Ces pratiques accompagnent leur quête de guérison et de protection.",
    },
    {
      id: "c2-q10",
      question: "Que fait boire Lalla Zoubida à son fils une fois au sanctuaire ?",
      choix: ["Du lait", "L'eau du sanctuaire", "Du thé à la menthe", "De l'eau de fleur d'oranger"],
      reponseCorrecte: 1,
      explication: "Elle lui fait boire l'eau du sanctuaire, censée porter bénédiction.",
    },
    {
      id: "c2-q11",
      question: "Pourquoi le groupe rentre-t-il précipitamment à la maison ?",
      choix: [
        "À cause de la pluie",
        "À cause de la blessure de Sidi Mohammed",
        "Parce que le sanctuaire ferme",
        "Parce que Rahma se sent mal",
      ],
      reponseCorrecte: 1,
      explication: "La griffure du chat précipite le retour à la maison.",
    },
    {
      id: "c2-q12",
      question: "Que fait le narrateur pendant ses deux jours et demi de repos ?",
      choix: [
        "Il retourne quand même au Msid",
        "Il observe les occupations des femmes pendant les matinées",
        "Il reste seul, sans personne autour de lui",
        "Il part chez Lalla Aïcha",
      ],
      reponseCorrecte: 1,
      explication: "Resté à la maison, il observe la vie quotidienne des femmes.",
    },
    {
      id: "c2-q13",
      question: "Qui offre les deux beignets au narrateur pendant sa convalescence ?",
      choix: ["Rahma", "Lalla Aïcha", "Fatma Bziouya", "La Chouafa"],
      reponseCorrecte: 2,
      explication: "Fatma Bziouya lui offre deux beignets, en plus du cabochon de verre offert par Rahma.",
    },
    {
      id: "c2-q14",
      question: "Que changent Lalla Zoubida, Rahma et Sidi Mohammed avant de partir pour le sanctuaire ?",
      choix: ["Rien de particulier", "Leurs vêtements", "Leurs chaussures uniquement", "Leur itinéraire habituel"],
      reponseCorrecte: 1,
      explication: "Le trio change de vêtements avant de prendre le chemin du mausolée.",
    },
    {
      id: "c2-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La peur de la mort", "La superstition et les croyances populaires", "Le mariage", "Le commerce"],
      reponseCorrecte: 1,
      explication: "Tout le chapitre tourne autour des croyances et pratiques superstitieuses liées au pèlerinage.",
    },
  ],
  3: [
    {
      id: "c3-q1",
      question: "Quel objet émerveille Lalla Zoubida chez Fatma Bziouya ?",
      choix: ["Un miroir", "Une lampe à pétrole", "Un tapis", "Un bijou en or"],
      reponseCorrecte: 1,
      explication:
        "Éblouie par la lampe à pétrole de sa voisine, elle finit par convaincre son mari que les bougies ne servent plus à rien.",
    },
    {
      id: "c3-q2",
      question: "Où Rahma se rendait-elle quand elle a perdu sa fille Zineb ?",
      choix: [
        "Au souk pour faire des courses",
        "Chez sa sœur Khadija, pour le baptême de son enfant",
        "Au sanctuaire de Sidi Ali Boughaleb",
        "Chez Lalla Aïcha",
      ],
      reponseCorrecte: 1,
      explication: "Rahma perd Zineb en se rendant chez sa sœur Khadija pour le baptême de son enfant.",
    },
    {
      id: "c3-q3",
      question: "Où Zineb est-elle finalement retrouvée ?",
      choix: [
        "Dans un asile, la maison des Idrissides à Dar Kitoun",
        "Chez le fqih",
        "Au bain maure",
        "Chez Fatma Bziouya",
      ],
      reponseCorrecte: 0,
      explication: "Après une longue recherche dans la médina, Lalla Zoubida la retrouve à Dar Kitoun.",
    },
    {
      id: "c3-q4",
      question: "Que fait Rahma pour remercier Dieu d'avoir retrouvé sa fille ?",
      choix: [
        "Elle offre un cadeau à Lalla Zoubida",
        "Elle organise un repas pour les pauvres et les mendiants aveugles",
        "Elle se rend en pèlerinage",
        "Elle achète une lampe à pétrole",
      ],
      reponseCorrecte: 1,
      explication: "Toutes les femmes s'entraident pour préparer ce repas de remerciement.",
    },
    {
      id: "c3-q5",
      question: "Comment se comportent les objets de la boîte à merveilles à la toute fin du chapitre ?",
      choix: [
        "Ils brillent plus que jamais",
        "Ils restent maussades et refusent de parler à l'enfant",
        "L'enfant en perd un",
        "Le père y ajoute un nouvel objet",
      ],
      reponseCorrecte: 1,
      explication: "Ce jour-là, exceptionnellement, les objets de la boîte restent silencieux.",
    },
    {
      id: "c3-q6",
      question: "Que décrit le narrateur en retournant au Msid après sa convalescence ?",
      choix: [
        "Une journée de congé",
        "Une séance particulièrement dure de l'apprentissage",
        "L'arrivée d'un nouvel élève",
        "Une fête surprise",
      ],
      reponseCorrecte: 1,
      explication: "Le retour au Msid se fait par une séance d'apprentissage particulièrement éprouvante.",
    },
    {
      id: "c3-q7",
      question: "Qui convainc Lalla Zoubida de l'utilité de la lampe à pétrole ?",
      choix: ["Rahma", "Fatma Bziouya", "Lalla Aïcha", "La Chouafa"],
      reponseCorrecte: 1,
      explication: "Fatma Bziouya, sa voisine, finit par la persuader d'en acheter une.",
    },
    {
      id: "c3-q8",
      question: "Que déclare Lalla Zoubida à son mari à propos des bougies, un soir où leur lumière faiblit ?",
      choix: [
        "Qu'elles sont trop chères",
        "Qu'elles ne servent plus à rien face à la lampe à pétrole",
        "Qu'il faut en acheter davantage",
        "Qu'elle préfère l'obscurité",
      ],
      reponseCorrecte: 1,
      explication: "Elle profite du dîner pour convaincre Maâlem Abdeslem que la lampe à pétrole est bien meilleure.",
    },
    {
      id: "c3-q9",
      question: "Pourquoi Sidi Mohammed pleure-t-il pendant que les femmes réconfortent Rahma ?",
      choix: ["Parce qu'il a peur", "Parce qu'il a faim", "Parce qu'il est malade", "Parce qu'on le gronde"],
      reponseCorrecte: 1,
      explication: "Contrairement aux femmes bouleversées par la disparition de Zineb, l'enfant pleure simplement de faim.",
    },
    {
      id: "c3-q10",
      question: "Comment les femmes réagissent-elles collectivement à la disparition de Zineb ?",
      choix: [
        "Elles restent indifférentes",
        "Elles se rassemblent pour réconforter Rahma et l'exhorter à la patience",
        "Elles accusent Rahma d'imprudence",
        "Elles préviennent immédiatement les autorités",
      ],
      reponseCorrecte: 1,
      explication: "La solidarité féminine se manifeste pleinement autour de la douleur de Rahma.",
    },
    {
      id: "c3-q11",
      question: "Que font les femmes après le départ des mendiants aveugles venus pour le repas ?",
      choix: [
        "Elles rangent la maison en silence",
        "Elles revêtent leurs caftans et improvisent une petite fête",
        "Elles partent se coucher",
        "Elles retournent au Msid",
      ],
      reponseCorrecte: 1,
      explication: "Le soulagement d'avoir retrouvé Zineb se prolonge en une petite fête entre voisines.",
    },
    {
      id: "c3-q12",
      question: "Qui est Khadija, mentionnée dans ce chapitre ?",
      choix: ["La voisine de Lalla Aïcha", "La sœur de Rahma", "La femme du fqih", "La fille de Fatma Bziouya"],
      reponseCorrecte: 1,
      explication: "Khadija, sœur de Rahma, organisait le baptême auquel Rahma se rendait.",
    },
    {
      id: "c3-q13",
      question: "Où était accrochée la lampe à pétrole qui émerveille Lalla Zoubida ?",
      choix: [
        "Dans la chambre de Fatma Bziouya",
        "Dans la chambre de Rahma",
        "Au Msid",
        "Chez Lalla Aïcha",
      ],
      reponseCorrecte: 0,
      explication: "C'est en visitant la chambre de sa voisine Fatma Bziouya que Lalla Zoubida la découvre.",
    },
    {
      id: "c3-q14",
      question: "Où Lalla Zoubida cherche-t-elle Zineb avant de la retrouver ?",
      choix: [
        "Uniquement au Msid",
        "Dans différents endroits de la médina de Fès",
        "Chez le voyant",
        "Au souk des bijoutiers",
      ],
      reponseCorrecte: 1,
      explication: "La recherche est longue et se déroule dans toute la médina.",
    },
    {
      id: "c3-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La peur de la perte", "Le mariage", "La fête de l'Achoura", "La malhonnêteté"],
      reponseCorrecte: 0,
      explication: "La disparition puis les retrouvailles de Zineb placent la peur de la perte au cœur du chapitre.",
    },
  ],
  4: [
    {
      id: "c4-q1",
      question: "À quelle saison se déroule la visite chez Lalla Aïcha ?",
      choix: ["L'hiver", "Le printemps", "L'été", "L'automne"],
      reponseCorrecte: 1,
      explication: "Le chapitre s'ouvre sur le début de la saison du printemps.",
    },
    {
      id: "c4-q2",
      question: "À quel jeu les enfants jouent-ils, qui se termine en dispute ?",
      choix: ["Le jeu de la mariée", "Le jeu du fqih", "Le jeu du marchand", "Le jeu de cache-cache"],
      reponseCorrecte: 0,
      explication: "Le jeu de la mariée, auquel participe le narrateur, se termine par une dispute entre enfants.",
    },
    {
      id: "c4-q3",
      question: "Qui a escroqué Moulay Larbi, le mari de Lalla Aïcha ?",
      choix: ["Le fqih", "Son associé Abdelkader", "Le coiffeur", "Un marchand du souk"],
      reponseCorrecte: 1,
      explication: "Moulay Larbi a été escroqué par son associé Abdelkader.",
    },
    {
      id: "c4-q4",
      question: "Le soir, quelles histoires le père raconte-t-il à son fils ?",
      choix: [
        "Les histoires fabuleuses d'Abdellah l'épicier",
        "Sa propre enfance",
        "L'histoire du sanctuaire de Sidi Ali Boughaleb",
        "Les malheurs de Moulay Larbi",
      ],
      reponseCorrecte: 0,
      explication: "Maâlem Abdeslem raconte à son fils les histoires fabuleuses d'Abdellah l'épicier.",
    },
    {
      id: "c4-q5",
      question: "Que fait Lalla Zoubida le lendemain, malgré la confidence demandée par Lalla Aïcha ?",
      choix: [
        "Elle garde le secret",
        "Elle raconte les malheurs de Lalla Aïcha à son propre mari",
        "Elle rend visite au voyant",
        "Elle part chez Rahma",
      ],
      reponseCorrecte: 1,
      explication: "Lalla Zoubida ne résiste pas à raconter l'histoire à Maâlem Abdeslem.",
    },
    {
      id: "c4-q6",
      question: "Qui est Lalla Aïcha pour Lalla Zoubida ?",
      choix: ["Sa sœur", "Une ancienne voisine, son amie intime", "Sa belle-mère", "Une inconnue"],
      reponseCorrecte: 1,
      explication: "Lalla Aïcha est une ancienne voisine devenue l'amie intime de Lalla Zoubida.",
    },
    {
      id: "c4-q7",
      question: "Comment les deux femmes passent-elles principalement leur journée chez Lalla Aïcha ?",
      choix: [
        "À cuisiner toute la journée",
        "À médire et à débiner les gens",
        "À réciter le Coran",
        "À préparer des vêtements",
      ],
      reponseCorrecte: 1,
      explication: "Comme la plupart des femmes, elles passent la journée à bavarder et à médire.",
    },
    {
      id: "c4-q8",
      question: "Avec qui le narrateur joue-t-il pendant que les femmes bavardent ?",
      choix: ["Il reste seul", "Avec les enfants de la maison", "Avec son père", "Avec le fqih"],
      reponseCorrecte: 1,
      explication: "Il rejoint les enfants de la maison pour participer à leurs jeux.",
    },
    {
      id: "c4-q9",
      question: "Que fait l'épouse de Moulay Larbi en le voyant revenir inopinément ?",
      choix: ["Elle se met en colère", "Elle se met à pleurer", "Elle sort de la maison", "Elle ne réagit pas"],
      reponseCorrecte: 1,
      explication: "Bouleversée, elle fond en larmes devant ce retour inattendu.",
    },
    {
      id: "c4-q10",
      question: "Qui console l'épouse de Moulay Larbi ?",
      choix: ["Fatma Bziouya", "Lalla Zoubida, son amie intime", "Rahma", "La Chouafa"],
      reponseCorrecte: 1,
      explication: "Lalla Zoubida, en amie proche, réconforte Lalla Aïcha.",
    },
    {
      id: "c4-q11",
      question: "Que permet la boîte à merveilles au narrateur, dans ce chapitre ?",
      choix: [
        "De gagner de l'argent",
        "De se débarrasser des contraintes du monde réel",
        "De guérir plus vite",
        "De se faire des amis",
      ],
      reponseCorrecte: 1,
      explication: "Comme souvent dans le roman, elle offre à l'enfant une échappatoire au réel.",
    },
    {
      id: "c4-q12",
      question: "Qui raconte à Lalla Zoubida le problème de Moulay Larbi, escroqué par son associé ?",
      choix: ["Rahma", "Lalla Aïcha", "Fatma Bziouya", "Le fqih"],
      reponseCorrecte: 1,
      explication: "C'est Lalla Aïcha elle-même qui confie ce malheur à son amie.",
    },
    {
      id: "c4-q13",
      question: "Qui raconte des histoires fabuleuses au narrateur le soir de ce chapitre ?",
      choix: ["Sa mère", "Son père, Maâlem Abdeslem", "Le fqih", "Rahma"],
      reponseCorrecte: 1,
      explication: "Maâlem Abdeslem raconte à son fils les histoires fabuleuses d'Abdellah l'épicier.",
    },
    {
      id: "c4-q14",
      question: "Comment se termine le jeu de la mariée auquel participe le narrateur ?",
      choix: ["Par une chanson", "Par une dispute", "Par un cadeau", "Par un repas"],
      reponseCorrecte: 1,
      explication: "Ce jeu d'enfants, comme souvent dans le roman, tourne à la dispute.",
    },
    {
      id: "c4-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: [
        "Le monde des femmes (bavardage et solidarité)",
        "La peur de la mort",
        "Le commerce et le marchandage",
        "La religiosité populaire",
      ],
      reponseCorrecte: 0,
      explication: "Le bavardage et la solidarité entre Lalla Zoubida et Lalla Aïcha structurent tout le chapitre.",
    },
  ],
  5: [
    {
      id: "c5-q1",
      question: "Qui meurt dans ce chapitre et bouleverse profondément le narrateur ?",
      choix: ["Le fqih", "Sidi Mohammed Ben Taher, le coiffeur", "L'oncle Othmane", "Maâlem Abdeslem"],
      reponseCorrecte: 1,
      explication: "La mort du coiffeur Sidi Mohammed Ben Taher plonge tout le quartier dans le deuil.",
    },
    {
      id: "c5-q2",
      question: "Quel effet cette mort a-t-elle sur l'enfant ?",
      choix: [
        "Il l'oublie très vite",
        "Il fait des cauchemars et devient peureux face à la mort",
        "Il refuse de retourner au Msid",
        "Il tombe malade physiquement",
      ],
      reponseCorrecte: 1,
      explication: "Pour avoir assisté aux honneurs funèbres, le narrateur fait des cauchemars et redoute la mort.",
    },
    {
      id: "c5-q3",
      question: "Quel cadeau Lalla Zoubida offre-t-elle à son fils pour le réconforter ?",
      choix: ["Un cabochon de verre", "Une chaînette en or", "Un jouet", "Un livre"],
      reponseCorrecte: 1,
      explication: "Cette chaînette en or fascine beaucoup le petit garçon de six ans.",
    },
    {
      id: "c5-q4",
      question: "Qu'est-ce qui déclenche la bagarre entre Sidi Mohammed et Zineb à la fin du chapitre ?",
      choix: [
        "Le chat de Zineb vole la chaîne en or de Sidi Mohammed",
        "Un désaccord sur un jeu",
        "Zineb casse un objet de la boîte à merveilles",
        "Une dispute au Msid",
      ],
      reponseCorrecte: 0,
      explication: "Le chat de Zineb dérobe la chaîne, provoquant une violente bagarre entre les deux enfants.",
    },
    {
      id: "c5-q5",
      question: "Quelle fête le fqih annonce-t-il à ses écoliers, visiblement heureux, au début du chapitre ?",
      choix: ["Le Mawlid", "L'Achoura", "L'Aïd al-Fitr", "Le mariage d'un voisin"],
      reponseCorrecte: 1,
      explication: "Deux semaines avant l'Achoura, le fqih annonce ses projets pour cette fête religieuse annuelle.",
    },
    {
      id: "c5-q6",
      question: "À qui Lalla Zoubida raconte-t-elle les malheurs de Lalla Aïcha et Moulay Larbi, en exigeant le secret ?",
      choix: ["Au fqih puis à son mari", "À Fatma Bziouya, puis à Rahma", "À la Chouafa uniquement", "À Zineb"],
      reponseCorrecte: 1,
      explication: "Elle confie cette histoire aux habitantes de Dar Chouafa, en leur faisant promettre le secret.",
    },
    {
      id: "c5-q7",
      question: "Qu'est-ce qui bouleverse toutes les femmes de la maison, un jour, par des cris et des hurlements ?",
      choix: ["Une dispute", "La mort du coiffeur", "Un vol", "Un incendie"],
      reponseCorrecte: 1,
      explication: "Ces cris annoncent la mort brutale de Sidi Mohammed Ben Taher.",
    },
    {
      id: "c5-q8",
      question: "Que font toutes les femmes après la mort du coiffeur ?",
      choix: [
        "Elles ignorent l'événement",
        "Elles présentent leurs condoléances à sa veuve",
        "Elles organisent une fête",
        "Elles quittent la maison",
      ],
      reponseCorrecte: 1,
      explication: "Toutes les femmes de Dar Chouafa se rendent auprès de la veuve pour la soutenir.",
    },
    {
      id: "c5-q9",
      question: "Qui essaie de réconforter l'enfant après la mort du coiffeur, sans succès ?",
      choix: ["Lalla Zoubida, par un cadeau", "Maâlem Abdeslem, en lui racontant une histoire", "Rahma", "Le fqih"],
      reponseCorrecte: 1,
      explication: "Malgré l'histoire racontée par son père, les scènes de la mort restent gravées dans sa mémoire.",
    },
    {
      id: "c5-q10",
      question: "Quel âge a Sidi Mohammed quand il reçoit la chaînette en or ?",
      choix: ["Quatre ans", "Cinq ans", "Six ans", "Huit ans"],
      reponseCorrecte: 2,
      explication: "Le texte précise qu'il s'agit du petit garçon de six ans.",
    },
    {
      id: "c5-q11",
      question: "Quel effet les scènes de la mort laissent-elles sur la mémoire de l'enfant ?",
      choix: ["Aucun effet durable", "Elles y restent gravées", "Il les oublie en une nuit", "Elles le font rire"],
      reponseCorrecte: 1,
      explication: "Malgré les efforts de son père, ces scènes marquent durablement l'enfant.",
    },
    {
      id: "c5-q12",
      question: "Quel lien de parenté Zineb a-t-elle avec Rahma ?",
      choix: ["Sa nièce", "Sa fille", "Sa sœur", "Sa voisine seulement"],
      reponseCorrecte: 1,
      explication: "Zineb est la fille de Rahma, déjà présente dans les chapitres précédents.",
    },
    {
      id: "c5-q13",
      question: "Combien de temps avant l'Achoura le fqih annonce-t-il ses projets à ses écoliers ?",
      choix: ["Une semaine", "Deux semaines", "Un mois", "Trois jours"],
      reponseCorrecte: 1,
      explication: "Le chapitre s'ouvre deux semaines avant la fête de l'Achoura.",
    },
    {
      id: "c5-q14",
      question: "Quel effet la mort du coiffeur a-t-elle sur les nuits du narrateur ?",
      choix: ["Il dort mieux qu'avant", "Il fait des cauchemars", "Il ne change rien", "Il refuse de dormir seul"],
      reponseCorrecte: 1,
      explication: "Le narrateur fait des cauchemars la nuit après avoir assisté aux honneurs funèbres.",
    },
    {
      id: "c5-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La peur de la mort", "Le commerce", "La fête de l'Achoura", "Le mariage"],
      reponseCorrecte: 0,
      explication: "La mort du coiffeur et son effet sur l'enfant placent la peur de la mort au centre du chapitre.",
    },
  ],
  6: [
    {
      id: "c6-q1",
      question: "Où Lalla Zoubida emmène-t-elle son fils pour lui acheter des vêtements neufs ?",
      choix: ["Au souk des bijoutiers", "À la Kissaria", "Chez le voyant", "Au mausolée"],
      reponseCorrecte: 1,
      explication: "Sidi Mohammed accompagne sa mère à la Kissaria pour l'Achoura.",
    },
    {
      id: "c6-q2",
      question: "Que réussit à faire Lalla Zoubida au souk grâce à son habileté ?",
      choix: [
        "Obtenir un gilet gratuitement",
        "Marchander et acheter un gilet au prix qui lui convient",
        "Échanger la lampe à pétrole",
        "Convaincre un marchand de la suivre à la maison",
      ],
      reponseCorrecte: 1,
      explication: "Les marchands présentent plusieurs gilets, et elle en obtient un au prix voulu.",
    },
    {
      id: "c6-q3",
      question: "Pourquoi Lalla Zoubida se met-elle en colère contre les deux enfants ?",
      choix: [
        "Ils ont sali leurs habits neufs",
        "Ils se sont perdus au souk",
        "Ils échangent des grimaces horribles",
        "Ils ont cassé un objet de la boîte à merveilles",
      ],
      reponseCorrecte: 2,
      explication: "Les grimaces horribles échangées entre les enfants provoquent la colère de la mère.",
    },
    {
      id: "c6-q4",
      question: "Quelle histoire Rahma raconte-t-elle aux voisines à la fin du chapitre ?",
      choix: [
        "Celle du voyant Sidi El Arafi",
        "Celle de l'oncle Othmane et de son épouse Lalla Khadija",
        "Celle du coiffeur défunt",
        "Celle de Moulay Larbi",
      ],
      reponseCorrecte: 1,
      explication: "Ce récit captive toutes les femmes réunies.",
    },
    {
      id: "c6-q5",
      question: "Pourquoi le fqih forme-t-il de nouvelles équipes au Msid ?",
      choix: [
        "Pour préparer un examen",
        "Pour organiser les festivités et mettre fin au désordre",
        "Pour punir les élèves indisciplinés",
        "Pour accueillir de nouveaux écoliers",
      ],
      reponseCorrecte: 1,
      explication: "Huit jours avant l'Achoura, le tumulte des préparatifs pousse le fqih à s'organiser.",
    },
    {
      id: "c6-q6",
      question: "Combien de jours avant l'Achoura les préparatifs commencent-ils au Msid ?",
      choix: ["Trois jours", "Huit jours", "Quinze jours", "Un mois"],
      reponseCorrecte: 1,
      explication: "Le chapitre s'ouvre huit jours avant la fête de l'Achoura.",
    },
    {
      id: "c6-q7",
      question: "Comment est décrite l'ambiance du Msid au début des préparatifs ?",
      choix: ["Calme et silencieuse", "Un tumulte strident et insupportable", "Triste", "Ordonnée dès le premier jour"],
      reponseCorrecte: 1,
      explication: "L'excitation des élèves crée un désordre que le fqih doit canaliser.",
    },
    {
      id: "c6-q8",
      question: "Qui Lalla Zoubida croise-t-elle en chemin vers la Kissaria ?",
      choix: ["Rahma", "Une amie de Lalla Aïcha", "Fatma Bziouya", "Le voyant"],
      reponseCorrecte: 1,
      explication: "Elle en profite pour lui raconter le sacrifice récent de Lalla Aïcha.",
    },
    {
      id: "c6-q9",
      question: "Comment le narrateur décrit-il le souk dans ce chapitre ?",
      choix: [
        "Un lieu vide et silencieux",
        "Un lieu grouillant de monde, avec ses boutiques et ses marchands",
        "Un lieu dangereux à éviter",
        "Un lieu réservé aux hommes uniquement",
      ],
      reponseCorrecte: 1,
      explication: "Le narrateur prend le temps de décrire l'animation du souk et le comportement des marchands.",
    },
    {
      id: "c6-q10",
      question: "Qu'imagine le narrateur en rentrant à la maison avec ses nouveaux habits ?",
      choix: [
        "Qu'il va les perdre",
        "Qu'il les porte déjà pour l'Achoura",
        "Qu'il doit les rendre",
        "Qu'ils ne lui vont pas",
      ],
      reponseCorrecte: 1,
      explication: "Il s'imagine déjà porter fièrement ses nouveaux habits d'Achoura.",
    },
    {
      id: "c6-q11",
      question: "Que fait le petit garçon, triste, après la colère de sa mère ?",
      choix: [
        "Il se réfugie dans ses rêveries et ses histoires fabuleuses",
        "Il quitte la maison",
        "Il va se plaindre à son père",
        "Il casse un objet",
      ],
      reponseCorrecte: 0,
      explication: "Comme souvent, l'imaginaire devient un refuge face à la contrariété.",
    },
    {
      id: "c6-q12",
      question: "Qui est Lalla Khadija, mentionnée à la fin du chapitre ?",
      choix: ["La voisine de Rahma", "L'épouse de l'oncle Othmane", "La fille du coiffeur", "La femme du fqih"],
      reponseCorrecte: 1,
      explication: "Lalla Khadija est l'épouse de l'oncle Othmane, dont Rahma raconte l'histoire.",
    },
    {
      id: "c6-q13",
      question: "Qu'est-ce qui provoque précisément la colère de Lalla Zoubida envers les deux enfants ?",
      choix: [
        "Des grimaces horribles échangées entre eux",
        "Une chanson trop bruyante",
        "Un vêtement déchiré",
        "Un jouet cassé",
      ],
      reponseCorrecte: 0,
      explication: "L'échange de grimaces entre les enfants met la mère en colère.",
    },
    {
      id: "c6-q14",
      question: "Que remarque le narrateur à propos du comportement des marchands du souk ?",
      choix: [
        "Ils sont malhonnêtes",
        "Ils ont de bonnes manières",
        "Ils ignorent les clientes",
        "Ils se disputent entre eux",
      ],
      reponseCorrecte: 1,
      explication: "Le narrateur souligne le bon comportement des marchands envers Lalla Zoubida.",
    },
    {
      id: "c6-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: [
        "La préparation collective d'une fête (l'Achoura)",
        "La peur de la mort",
        "Le mariage",
        "La religiosité populaire seule",
      ],
      reponseCorrecte: 0,
      explication: "Tout le chapitre tourne autour des préparatifs collectifs de l'Achoura.",
    },
  ],
  7: [
    {
      id: "c7-q1",
      question: "Qui informe Sidi Mohammed qu'il doit rejoindre ses camarades au Msid ?",
      choix: ["Le fqih en personne", "Hamoussa, un élève de petite taille", "Son père", "Zineb"],
      reponseCorrecte: 1,
      explication: "Hamoussa vient le prévenir des derniers préparatifs de l'Achoura.",
    },
    {
      id: "c7-q2",
      question: "Où le père emmène-t-il son fils après lui avoir acheté des jouets ?",
      choix: ["Au souk des bijoutiers", "Chez le coiffeur", "Au sanctuaire", "Chez Lalla Aïcha"],
      reponseCorrecte: 1,
      explication: "Le narrateur s'ennuie devant les conversations des adultes chez le coiffeur.",
    },
    {
      id: "c7-q3",
      question: "Que font les écoliers le jour de l'Achoura au Msid ?",
      choix: [
        "Ils partent en pèlerinage",
        "Ils récitent le Coran, chantent des cantiques et font des invocations",
        "Ils reçoivent des cadeaux du fqih",
        "Ils jouent toute la journée",
      ],
      reponseCorrecte: 1,
      explication: "C'est une journée exceptionnelle célébrée collectivement au Msid.",
    },
    {
      id: "c7-q4",
      question: "Qui rend une visite surprise à Lalla Zoubida l'après-midi de l'Achoura ?",
      choix: ["Rahma", "Fatma Bziouya", "Lalla Aïcha", "La Chouafa"],
      reponseCorrecte: 2,
      explication: "Les deux amies passent alors la journée à bavarder.",
    },
    {
      id: "c7-q5",
      question: "Où se rassemblent les femmes le soir de l'Achoura pour chanter ?",
      choix: ["Au Msid", "Sur les terrasses", "Au souk", "Dans la rue"],
      reponseCorrecte: 1,
      explication: "Toutes les terrasses se remplissent de femmes qui chantent, avant que l'enfant ne retrouve sa boîte.",
    },
    {
      id: "c7-q6",
      question: "Que font les femmes deux jours avant l'Achoura, selon le narrateur ?",
      choix: [
        "Elles préparent le repas de fête",
        "Elles achètent des tambourins et des bendirs et essaient leurs instruments",
        "Elles se rendent au sanctuaire",
        "Elles cousent des vêtements",
      ],
      reponseCorrecte: 1,
      explication: "L'ambiance de fête se manifeste déjà par ces achats et ces essais musicaux.",
    },
    {
      id: "c7-q7",
      question: "Où le père emmène-t-il d'abord son fils, avant le coiffeur ?",
      choix: ["Chez les marchands de jouets", "Au sanctuaire", "Chez le fqih", "Au souk des bijoutiers"],
      reponseCorrecte: 0,
      explication: "Maâlem Abdeslem achète d'abord des jouets à son fils.",
    },
    {
      id: "c7-q8",
      question: "Que ressent le narrateur pendant que son père discute chez le coiffeur ?",
      choix: ["De la joie", "De l'ennui, face aux conversations des adultes", "De la peur", "De la fierté"],
      reponseCorrecte: 1,
      explication: "Les conversations d'adultes chez le coiffeur ennuient profondément l'enfant.",
    },
    {
      id: "c7-q9",
      question: "Que porte le narrateur le jour de l'Achoura pour se rendre au Msid ?",
      choix: ["Ses habits de tous les jours", "Ses vêtements neufs", "Un déguisement", "Les habits de son père"],
      reponseCorrecte: 1,
      explication: "Il revêt ses vêtements neufs achetés à la Kissaria au chapitre précédent.",
    },
    {
      id: "c7-q10",
      question: "Avec qui le narrateur se rend-il au Msid le jour de l'Achoura ?",
      choix: ["Sa mère", "Son père", "Hamoussa seul", "Lalla Aïcha"],
      reponseCorrecte: 1,
      explication: "Il accompagne son père pour célébrer cette fête particulière au Msid.",
    },
    {
      id: "c7-q11",
      question: "En plus de réciter le Coran, que font les écoliers ensemble ce jour-là ?",
      choix: [
        "Ils font une sieste collective",
        "Ils chantent des cantiques et font des invocations",
        "Ils reçoivent des notes",
        "Ils quittent le Msid plus tôt",
      ],
      reponseCorrecte: 1,
      explication: "La journée de l'Achoura au Msid est marquée par les chants et les invocations collectives.",
    },
    {
      id: "c7-q12",
      question: "Que font Lalla Aïcha et Lalla Zoubida après le déjeuner, le jour de l'Achoura ?",
      choix: ["Elles vont au souk", "Elles passent la journée à bavarder", "Elles dorment", "Elles cuisinent"],
      reponseCorrecte: 1,
      explication: "La visite surprise de Lalla Aïcha se prolonge en un long bavardage entre amies.",
    },
    {
      id: "c7-q13",
      question: "Par quoi le chapitre se termine-t-il, une fois la soirée de l'Achoura passée ?",
      choix: [
        "Une bagarre",
        "Le retour de Sidi Mohammed à sa boîte à merveilles",
        "L'annonce d'un mariage",
        "Le départ de Lalla Aïcha",
      ],
      reponseCorrecte: 1,
      explication: "Comme souvent après une journée mouvementée, le récit se referme sur la boîte à merveilles.",
    },
    {
      id: "c7-q14",
      question: "Qui est Hamoussa, mentionné au début du chapitre ?",
      choix: ["Un marchand du souk", "Un élève de petite taille", "Le frère de Zineb", "Un voisin adulte"],
      reponseCorrecte: 1,
      explication: "Hamoussa, petit élève du Msid, vient prévenir Sidi Mohammed des derniers préparatifs.",
    },
    {
      id: "c7-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La fête collective de l'Achoura", "La peur de la mort", "Le mariage", "Les difficultés financières"],
      reponseCorrecte: 0,
      explication: "Toute la journée célébrée dans ce chapitre tourne autour de la fête collective de l'Achoura.",
    },
  ],
  8: [
    {
      id: "c8-q1",
      question: "Pourquoi le Msid change-t-il de lieu d'apprentissage dans ce chapitre ?",
      choix: [
        "Le Msid habituel est en travaux",
        "La chaleur pousse le fqih à déplacer la classe vers un vaste mausolée",
        "Le fqih déménage",
        "Trop d'élèves se sont inscrits",
      ],
      reponseCorrecte: 1,
      explication: "Ce nouveau lieu a un effet presque magique sur la mémoire du narrateur.",
    },
    {
      id: "c8-q2",
      question: "Pourquoi Maâlem Abdeslem se bat-il avec un courtier au souk des bijoutiers ?",
      choix: [
        "Le courtier l'insulte",
        "Le courtier tente de l'escroquer en changeant le prix des bracelets à la hausse",
        "Le courtier vole Fatma Bziouya",
        "Le courtier refuse de le servir",
      ],
      reponseCorrecte: 1,
      explication: "Cette malhonnêteté déclenche une bagarre qui chagrine profondément Lalla Zoubida.",
    },
    {
      id: "c8-q3",
      question: "Pourquoi Lalla Zoubida refuse-t-elle finalement les bracelets que son mari lui rapporte ?",
      choix: [
        "Ils ne lui plaisent pas",
        "Elle craint qu'ils portent malheur à la maison",
        "Ils sont trop chers",
        "Elle préfère une lampe à pétrole",
      ],
      reponseCorrecte: 1,
      explication: "Après la bagarre du souk, elle refuse les bracelets par superstition.",
    },
    {
      id: "c8-q4",
      question: "Qui accompagne Lalla Zoubida et son mari au souk des bijoutiers ?",
      choix: ["Rahma", "Fatma Bziouya", "Lalla Aïcha", "La Chouafa"],
      reponseCorrecte: 1,
      explication: "Fatma Bziouya rentre elle aussi chagrinée par la bagarre.",
    },
    {
      id: "c8-q5",
      question: "Qu'apprend Lalla Aïcha à Lalla Zoubida à la toute fin du chapitre ?",
      choix: [
        "Elle attend un enfant",
        "Son mari Moulay Larbi l'a abandonnée pour la fille d'Abderrahman le coiffeur",
        "Elle part vivre à la campagne",
        "Elle a retrouvé un travail",
      ],
      reponseCorrecte: 1,
      explication: "Ce nouveau malheur de Lalla Aïcha annonce le sujet du chapitre 11.",
    },
    {
      id: "c8-q6",
      question: "Contre quoi Lalla Aïcha déclare-t-elle une guerre acharnée, après l'Achoura ?",
      choix: ["La poussière", "Les mouches", "Le bruit", "Le froid"],
      reponseCorrecte: 1,
      explication: "Ce détail domestique ouvre le chapitre sur un ton presque léger, avant le drame du souk.",
    },
    {
      id: "c8-q7",
      question: "Quel effet le nouveau lieu d'apprentissage (le mausolée) a-t-il sur la mémoire du narrateur ?",
      choix: ["Aucun effet particulier", "Un effet presque magique", "Il l'endort", "Il le rend malade"],
      reponseCorrecte: 1,
      explication: "Le changement de cadre stimule étrangement la mémoire de l'enfant.",
    },
    {
      id: "c8-q8",
      question: "Que voulait acheter Maâlem Abdeslem à sa femme au souk des bijoutiers ?",
      choix: ["Un caftan", "Des bracelets qu'elle désirait", "Une lampe à pétrole", "Un cabochon de verre"],
      reponseCorrecte: 1,
      explication: "Il souhaitait offrir à Lalla Zoubida les bracelets qu'elle convoitait.",
    },
    {
      id: "c8-q9",
      question: "Comment Lalla Zoubida et Fatma Bziouya rentrent-elles à la maison après la bagarre ?",
      choix: ["Joyeuses", "Profondément chagrinées", "Indifférentes", "En retard"],
      reponseCorrecte: 1,
      explication: "La bagarre au souk les bouleverse profondément.",
    },
    {
      id: "c8-q10",
      question: "Qui est Abderrahman, mentionné à la fin du chapitre ?",
      choix: [
        "Le coiffeur dont la fille a épousé Moulay Larbi",
        "Le courtier malhonnête du souk",
        "Le nouveau fqih",
        "Un voisin de Dar Chouafa",
      ],
      reponseCorrecte: 0,
      explication: "Moulay Larbi s'est remarié avec la fille d'Abderrahman le coiffeur.",
    },
    {
      id: "c8-q11",
      question: "Qu'est-ce qui pousse le fqih à changer de lieu d'apprentissage en cette saison ?",
      choix: ["La pluie", "La chaleur", "Un conflit avec les parents", "Un déménagement du Msid"],
      reponseCorrecte: 1,
      explication: "C'est la chaleur qui rend nécessaire ce déplacement vers un lieu plus frais.",
    },
    {
      id: "c8-q12",
      question: "Que fait finalement Maâlem Abdeslem des bracelets, malgré la bagarre ?",
      choix: [
        "Il les revend aussitôt",
        "Il les rapporte quand même à sa femme",
        "Il les jette",
        "Il les offre à Fatma Bziouya",
      ],
      reponseCorrecte: 1,
      explication: "Il apporte tout de même les bracelets à Lalla Zoubida, qui finit par les refuser.",
    },
    {
      id: "c8-q13",
      question: "Quel est le nouveau malheur que Lalla Aïcha confie à Lalla Zoubida à la fin du chapitre ?",
      choix: [
        "Une maladie",
        "L'abandon de son mari pour la fille du coiffeur",
        "La perte d'un enfant",
        "Une dette impayée",
      ],
      reponseCorrecte: 1,
      explication: "Ce malheur conjugal sera développé plus longuement au chapitre 11.",
    },
    {
      id: "c8-q14",
      question: "Où se déroule la bagarre entre Maâlem Abdeslem et le courtier ?",
      choix: ["Au Msid", "Au souk des bijoutiers", "Chez Lalla Aïcha", "Au mausolée"],
      reponseCorrecte: 1,
      explication: "C'est au souk des bijoutiers, en achetant les bracelets, que la dispute éclate.",
    },
    {
      id: "c8-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La malhonnêteté et la superstition", "La fête de l'Achoura", "Le deuil", "Le monde des femmes"],
      reponseCorrecte: 0,
      explication: "La malhonnêteté du courtier et la superstition de Lalla Zoubida dominent ce chapitre.",
    },
  ],
  9: [
    {
      id: "c9-q1",
      question: "Que fait Maâlem Abdeslem après avoir perdu tout son capital au souk ?",
      choix: [
        "Il emprunte de l'argent à un voisin",
        "Il part travailler comme moissonneur aux environs de Fès",
        "Il ouvre aussitôt une nouvelle boutique",
        "Il consulte un voyant",
      ],
      reponseCorrecte: 1,
      explication: "Après sa faillite, il décide d'aller moissonner pour redresser la situation familiale.",
    },
    {
      id: "c9-q2",
      question: "Qui aide à préparer des remèdes pendant que Sidi Mohammed est malade ?",
      choix: ["Le fqih", "Les voisines", "Le voyant Sidi El Arafi", "Driss El Aouad"],
      reponseCorrecte: 1,
      explication: "Inquiètes, les voisines n'hésitent pas à préparer des remèdes pour sa guérison.",
    },
    {
      id: "c9-q3",
      question: "Chez qui Lalla Zoubida se rend-elle un après-midi, laissant son fils seul à la maison ?",
      choix: ["Chez Rahma", "Chez Fatma Bziouya", "Chez Lalla Aïcha", "Chez la Chouafa"],
      reponseCorrecte: 2,
      explication: "Le narrateur passe alors des moments affreux à attendre son retour.",
    },
    {
      id: "c9-q4",
      question: "Que propose Lalla Aïcha à son amie pour se débarrasser de leurs ennuis ?",
      choix: [
        "Un pèlerinage à Sidi Ali Boughaleb",
        "Consulter le voyant Sidi El Arafi",
        "Aller voir le fqih",
        "Organiser un repas pour les pauvres",
      ],
      reponseCorrecte: 1,
      explication: "Cette proposition annonce la visite au voyant du chapitre suivant.",
    },
    {
      id: "c9-q5",
      question: "Sur quoi le narrateur s'attarde-t-il en évoquant l'absence de son père ?",
      choix: [
        "La valeur et l'importance d'un père dans une famille",
        "Les dangers de la campagne",
        "Le prix du blé",
        "La colère de sa mère",
      ],
      reponseCorrecte: 0,
      explication: "L'absence de Maâlem Abdeslem laisse un vide qui pousse l'enfant à cette réflexion.",
    },
    {
      id: "c9-q6",
      question: "Que perd Maâlem Abdeslem au souk, provoquant sa faillite ?",
      choix: ["Une partie de son capital", "Tout son maigre capital", "Sa maison", "Ses outils de tisserand"],
      reponseCorrecte: 1,
      explication: "Il perd la totalité de son capital, déjà modeste.",
    },
    {
      id: "c9-q7",
      question: "Comment réagit Lalla Zoubida à l'annonce de la faillite ?",
      choix: ["Elle reste indifférente", "Elle se lamente", "Elle se met en colère contre son mari", "Elle part chez sa mère"],
      reponseCorrecte: 1,
      explication: "Bouleversée, elle se lamente face à cette nouvelle difficulté financière.",
    },
    {
      id: "c9-q8",
      question: "Que fait Maâlem Abdeslem pour rassurer sa femme malgré la faillite ?",
      choix: [
        "Il l'exhorte à la patience",
        "Il lui promet de ne plus travailler",
        "Il l'envoie chez sa famille",
        "Il refuse de lui parler",
      ],
      reponseCorrecte: 0,
      explication: "Il l'exhorte à la patience avant de décider de partir travailler comme moissonneur.",
    },
    {
      id: "c9-q9",
      question: "Que doit faire Sidi Mohammed pendant sa convalescence, sur ordre de sa mère ?",
      choix: ["Aller au Msid quand même", "Rester au lit", "Sortir prendre l'air", "Manger davantage"],
      reponseCorrecte: 1,
      explication: "Sa mère l'oblige à rester au lit malgré son impatience.",
    },
    {
      id: "c9-q10",
      question: "Comment le narrateur réagit-il aux papotages des femmes pendant sa maladie ?",
      choix: ["Avec beaucoup d'intérêt", "Avec indifférence", "Avec colère", "Il ne les entend pas"],
      reponseCorrecte: 1,
      explication: "Cloué au lit, il écoute ces papotages sans grand intérêt.",
    },
    {
      id: "c9-q11",
      question: "Comment Sidi Mohammed décrit-il la maison de Lalla Aïcha lors de cette visite ?",
      choix: [
        "Plus belle que jamais",
        "Comme ayant perdu son charme habituel",
        "Exactement comme d'habitude",
        "Il ne la décrit pas",
      ],
      reponseCorrecte: 1,
      explication: "La maison lui semble avoir perdu son charme, à l'image du malheur de son amie.",
    },
    {
      id: "c9-q12",
      question: "Sur quoi le narrateur médite-t-il en attendant seul le retour de sa mère ?",
      choix: ["Le jour et la nuit", "Le prix des bracelets", "Son avenir professionnel", "Le voyage de son père"],
      reponseCorrecte: 0,
      explication: "Seul et angoissé, l'enfant se met à méditer sur le passage du jour à la nuit.",
    },
    {
      id: "c9-q13",
      question: "Comment Lalla Aïcha accueille-t-elle la mère et le fils lors de leur visite ?",
      choix: ["Avec froideur", "Avec bienveillance", "Elle refuse de les recevoir", "Avec indifférence"],
      reponseCorrecte: 1,
      explication: "Malgré son propre malheur, Lalla Aïcha reçoit ses invités avec bienveillance.",
    },
    {
      id: "c9-q14",
      question: "Que fait Lalla Zoubida le lendemain de son après-midi passé seule chez Lalla Aïcha ?",
      choix: [
        "Elle annonce à son fils qu'ils iront chez Lalla Aïcha, qui les attend",
        "Elle refuse d'y retourner",
        "Elle part rejoindre son mari",
        "Elle consulte immédiatement le voyant",
      ],
      reponseCorrecte: 0,
      explication: "Elle annonce à Sidi Mohammed qu'ils se rendront ensemble chez Lalla Aïcha.",
    },
    {
      id: "c9-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: [
        "Les difficultés financières et l'absence du père",
        "La fête de l'Achoura",
        "Le mariage",
        "La peur de la mort",
      ],
      reponseCorrecte: 0,
      explication: "La faillite de Maâlem Abdeslem et son départ dominent tout le chapitre.",
    },
  ],
  10: [
    {
      id: "c10-q1",
      question: "À quoi Sidi Mohammed compare-t-il le panier du voyant Sidi El Arafi ?",
      choix: ["À un coffre au trésor", "À sa propre boîte à merveilles", "À un sac du marché", "À rien de particulier"],
      reponseCorrecte: 1,
      explication: "Cette comparaison lui fait retrouver le sourire, malgré sa peur initiale.",
    },
    {
      id: "c10-q2",
      question: "Comment le voyant engage-t-il la discussion avec ses visiteurs ?",
      choix: [
        "Il lit dans une boule de cristal",
        "Il leur fait tirer un objet du panier",
        "Il leur pose directement des questions",
        "Il récite des versets du Coran",
      ],
      reponseCorrecte: 1,
      explication: "Chaque objet tiré du panier sert de point de départ à ses paroles rassurantes.",
    },
    {
      id: "c10-q3",
      question: "Qui se met à pleurer pendant la consultation, avant d'être réconfortée par le voyant ?",
      choix: ["Lalla Zoubida", "Lalla Aïcha", "Rahma", "Fatma Bziouya"],
      reponseCorrecte: 1,
      explication: "Lalla Aïcha pleure au fil du discours de l'aveugle, qui la réconforte.",
    },
    {
      id: "c10-q4",
      question: "Pourquoi Sidi Mohammed se cache-t-il dans le haïk de sa mère, dans la rue ?",
      choix: [
        "Il a peur d'un chien",
        "Il aperçoit le fqih et prend peur",
        "Il pleut soudainement",
        "Il voit un mendiant",
      ],
      reponseCorrecte: 1,
      explication: "Sa mère lui reproche alors son attitude, alors qu'il dansait un instant plus tôt.",
    },
    {
      id: "c10-q5",
      question: "Qu'apporte le messager envoyé par Maâlem Abdeslem à la fin du chapitre ?",
      choix: [
        "L'annonce de son retour immédiat",
        "Des nouvelles, des pièces de monnaie et des provisions",
        "Une lettre du fqih",
        "Un cadeau pour Sidi Mohammed",
      ],
      reponseCorrecte: 1,
      explication: "Ces nouvelles rendent Lalla Zoubida toute heureuse et excitée.",
    },
    {
      id: "c10-q6",
      question: "Qui guide Lalla Zoubida et Lalla Aïcha jusqu'au logis de Sidi El Arafi ?",
      choix: ["Un enfant", "Le fqih", "Un marchand", "Driss El Aouad"],
      reponseCorrecte: 0,
      explication: "Un enfant les guide jusqu'au logis du voyant.",
    },
    {
      id: "c10-q7",
      question: "Comment Sidi El Arafi accueille-t-il ses visiteuses ?",
      choix: ["Avec méfiance", "Chaleureusement", "Avec indifférence", "Il refuse de les recevoir"],
      reponseCorrecte: 1,
      explication: "Le voyant les reçoit chaleureusement dès leur arrivée.",
    },
    {
      id: "c10-q8",
      question: "Qui apporte le panier à Sidi El Arafi ?",
      choix: ["Sa fille", "Sa femme", "Un élève du Msid", "Lalla Zoubida"],
      reponseCorrecte: 1,
      explication: "La femme du voyant aveugle lui apporte le panier utilisé pendant la consultation.",
    },
    {
      id: "c10-q9",
      question: "Comment Sidi Mohammed réagit-il d'abord en voyant le voyant ?",
      choix: ["Avec curiosité amusée", "Avec peur", "Avec indifférence", "Avec colère"],
      reponseCorrecte: 1,
      explication: "Il est d'abord peureux, avant de retrouver son sourire grâce au panier.",
    },
    {
      id: "c10-q10",
      question: "Que ressentent les femmes face aux paroles de Sidi El Arafi ?",
      choix: [
        "Elles restent sceptiques",
        "Elles sont profondément touchées, bouleversées dans leurs émotions",
        "Elles s'ennuient",
        "Elles rient beaucoup",
      ],
      reponseCorrecte: 1,
      explication: "Le discours du voyant bouleverse profondément Lalla Zoubida et Lalla Aïcha.",
    },
    {
      id: "c10-q11",
      question: "Comment les deux femmes ressortent-elles de la consultation ?",
      choix: ["Déçues", "Rassurées et satisfaites", "En colère", "Toujours aussi inquiètes"],
      reponseCorrecte: 1,
      explication: "Les conseils, prières et bénédictions du voyant les influencent positivement.",
    },
    {
      id: "c10-q12",
      question: "Que faisait Sidi Mohammed dans la rue juste avant d'apercevoir le fqih ?",
      choix: ["Il pleurait", "Il dansait", "Il courait après un chat", "Il dormait"],
      reponseCorrecte: 1,
      explication: "Il dansait joyeusement en présence de sa mère et de Lalla Aïcha.",
    },
    {
      id: "c10-q13",
      question: "Comment sa mère réagit-elle à son attitude craintive dans la rue ?",
      choix: ["Elle le rassure aussitôt", "Elle le lui reproche", "Elle ne remarque rien", "Elle rit avec lui"],
      reponseCorrecte: 1,
      explication: "Lalla Zoubida lui reproche de s'être caché dans son haïk devant le fqih.",
    },
    {
      id: "c10-q14",
      question: "Qui envoie le messager qui vient chercher la famille à la fin du chapitre ?",
      choix: ["Le fqih", "Maâlem Abdeslem", "Sidi El Arafi", "Driss El Aouad"],
      reponseCorrecte: 1,
      explication: "Le messager, envoyé par Maâlem Abdeslem, apporte de bonnes nouvelles du père.",
    },
    {
      id: "c10-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["La croyance et le recours au voyant", "Le mariage", "La fête de l'Achoura", "La malhonnêteté"],
      reponseCorrecte: 0,
      explication: "La consultation du voyant Sidi El Arafi structure l'ensemble de ce chapitre.",
    },
  ],
  11: [
    {
      id: "c11-q1",
      question: "Qui est Salama ?",
      choix: [
        "Une voisine venue se plaindre",
        "La marieuse professionnelle qui avait organisé le mariage de Moulay Larbi",
        "La sœur de Lalla Aïcha",
        "Une mendiante",
      ],
      reponseCorrecte: 1,
      explication: "Sidi Mohammed fait d'elle un portrait dévalorisant, à la voix d'homme.",
    },
    {
      id: "c11-q2",
      question: "Pourquoi Salama vient-elle demander pardon à Lalla Aïcha ?",
      choix: [
        "Elle a médit d'elle",
        "C'est elle qui a organisé le mariage raté de Moulay Larbi avec la fille du coiffeur",
        "Elle a emprunté de l'argent sans le rendre",
        "Elle a cassé un objet chez elle",
      ],
      reponseCorrecte: 1,
      explication: "Elle reconnaît son erreur dans le choix de cette union malheureuse.",
    },
    {
      id: "c11-q3",
      question: "Que reproche-t-on surtout à la belle-mère de Moulay Larbi ?",
      choix: [
        "Elle vole de l'argent",
        "Elle se mêle des affaires de sa fille et l'incite à être trop exigeante",
        "Elle refuse de recevoir Moulay Larbi",
        "Elle insulte les voisines",
      ],
      reponseCorrecte: 1,
      explication: "Cette ingérence rend la vie de Moulay Larbi insupportable.",
    },
    {
      id: "c11-q4",
      question: "Qui confirme les propos de Salama en qualifiant la fille du coiffeur de « folle » ?",
      choix: ["Fatma Bziouya", "Zhour", "Rahma", "La Chouafa"],
      reponseCorrecte: 1,
      explication: "Zhour raconte à son tour les difficultés quotidiennes subies par Moulay Larbi.",
    },
    {
      id: "c11-q5",
      question: "Pourquoi une dispute éclate-t-elle entre Sidi Mohammed et une voisine ?",
      choix: [
        "Il a cassé un objet",
        "Il a oublié de fermer la porte des toilettes",
        "Il a insulté son fils",
        "Il a renversé le thé",
      ],
      reponseCorrecte: 1,
      explication: "La voisine lui adresse alors des épithètes dépréciatifs.",
    },
    {
      id: "c11-q6",
      question: "Que prépare Lalla Aïcha en accueillant Lalla Zoubida ?",
      choix: ["Un repas complet", "Le thé", "Des pâtisseries uniquement", "Rien de particulier"],
      reponseCorrecte: 1,
      explication: "Elle reçoit son amie de bon cœur en préparant le thé.",
    },
    {
      id: "c11-q7",
      question: "Comment Sidi Mohammed décrit-il Salama à son arrivée ?",
      choix: [
        "De façon élogieuse",
        "De façon dévalorisante, avec une voix d'homme",
        "Comme une femme très douce",
        "Il ne la décrit pas",
      ],
      reponseCorrecte: 1,
      explication: "Le portrait que fait l'enfant de la marieuse est nettement dévalorisant.",
    },
    {
      id: "c11-q8",
      question: "Qu'est-ce que la fille du coiffeur multiplie, selon le récit de Salama ?",
      choix: ["Ses cadeaux", "Ses exigences", "Ses visites", "Ses excuses"],
      reponseCorrecte: 1,
      explication: "Ses exigences croissantes rendent la vie de couple de plus en plus difficile.",
    },
    {
      id: "c11-q9",
      question: "Comment se termine la scène chez Lalla Aïcha ?",
      choix: [
        "Par une réconciliation",
        "Par une violente diatribe collective contre la fille du coiffeur et sa famille",
        "Par le départ silencieux de Salama",
        "Par un repas partagé",
      ],
      reponseCorrecte: 1,
      explication: "Toutes les femmes présentes se liguent contre la fille du coiffeur.",
    },
    {
      id: "c11-q10",
      question: "Que fait Lalla Aïcha une deuxième fois pendant la discussion ?",
      choix: ["Elle sort de la pièce", "Elle prépare de nouveau le thé", "Elle gronde Sidi Mohammed", "Elle pleure"],
      reponseCorrecte: 1,
      explication: "Le thé est repréparé pendant que Salama poursuit son récit.",
    },
    {
      id: "c11-q11",
      question: "Quel mariage est au cœur des reproches de Salama et Zhour ?",
      choix: [
        "Celui de Moulay Larbi avec la fille du coiffeur",
        "Celui de Maâlem Abdeslem",
        "Celui de l'oncle Othmane",
        "Celui de Driss El Aouad",
      ],
      reponseCorrecte: 0,
      explication: "C'est ce mariage malheureux, organisé par Salama, qui est au centre du chapitre.",
    },
    {
      id: "c11-q12",
      question: "Qui est Zhour dans ce chapitre ?",
      choix: [
        "Une nouvelle voisine qui confirme les difficultés de Moulay Larbi",
        "La fille du coiffeur elle-même",
        "La femme de Maâlem Abdeslem",
        "La sœur de Salama",
      ],
      reponseCorrecte: 0,
      explication: "Zhour raconte à son tour les difficultés quotidiennes que subit Moulay Larbi.",
    },
    {
      id: "c11-q13",
      question: "Que reconnaît Salama en venant chez Lalla Aïcha ?",
      choix: ["Son erreur dans le mariage qu'elle a organisé", "Un vol commis", "Un mensonge ancien", "Une dette"],
      reponseCorrecte: 0,
      explication: "Elle vient demander pardon pour ce mariage raté qu'elle a elle-même arrangé.",
    },
    {
      id: "c11-q14",
      question: "Comment est décrite la voix de Salama ?",
      choix: ["Douce et fluette", "À la voix d'homme", "Chantante", "Inaudible"],
      reponseCorrecte: 1,
      explication: "Sidi Mohammed remarque particulièrement sa voix, comparable à celle d'un homme.",
    },
    {
      id: "c11-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["Le mariage et ses désillusions", "La fête de l'Achoura", "La peur de la mort", "Le commerce"],
      reponseCorrecte: 0,
      explication: "Le mariage raté de Moulay Larbi et ses conséquences dominent tout le chapitre.",
    },
  ],
  12: [
    {
      id: "c12-q1",
      question: "Qui annonce à la famille, tout excitée, avoir vu Maâlem Abdeslem dans la rue ?",
      choix: ["Fatma Bziouya", "Zineb", "Lalla Aïcha", "Le fqih"],
      reponseCorrecte: 1,
      explication: "Zineb, partie faire une course, revient précipitamment porter la bonne nouvelle.",
    },
    {
      id: "c12-q2",
      question: "Que rapporte le père à son retour de voyage ?",
      choix: [
        "De l'argent uniquement",
        "Deux poulets, des œufs, du beurre, de l'huile et des olives",
        "Un cadeau pour son fils seulement",
        "Rien, il rentre les mains vides",
      ],
      reponseCorrecte: 1,
      explication: "Ce retour chargé de provisions comble de joie toute la maisonnée.",
    },
    {
      id: "c12-q3",
      question: "Qui monte voir Maâlem Abdeslem pour parler de la séparation de Moulay Larbi ?",
      choix: ["Le fqih", "Driss El Aouad", "Abdellah l'épicier", "Le voyant Sidi El Arafi"],
      reponseCorrecte: 1,
      explication: "Les deux hommes s'entretiennent de cette séparation entamée au chapitre 8.",
    },
    {
      id: "c12-q4",
      question: "Que décide de faire Sidi Mohammed en écoutant les chants des femmes de Dar Chouafa ?",
      choix: [
        "Apprendre à jouer du bendir",
        "Composer ses propres chansons",
        "Rejoindre le Msid plus tôt",
        "Écrire une lettre à son père",
      ],
      reponseCorrecte: 1,
      explication: "Il intègre même le nom d'une femme à son propre chant.",
    },
    {
      id: "c12-q5",
      question: "Sur quel geste le roman se referme-t-il, à la toute dernière ligne ?",
      choix: [
        "Le mariage de Moulay Larbi",
        "Le retour du narrateur à sa boîte à merveilles",
        "Le départ du fqih",
        "La mort de la Chouafa",
      ],
      reponseCorrecte: 1,
      explication: "Après le retour du père, le récit se clôt sur ce geste symbolique de l'enfant.",
    },
    {
      id: "c12-q6",
      question: "Comment le narrateur perçoit-il les couplets entonnés par les femmes de Dar Chouafa ?",
      choix: ["Il les trouve ennuyeux", "Il les apprécie pour leur sérénité", "Il ne les écoute pas", "Il les trouve tristes"],
      reponseCorrecte: 1,
      explication: "Ces chants, admirés pour leur sérénité, l'inspirent à composer les siens.",
    },
    {
      id: "c12-q7",
      question: "Que choisit d'intégrer le narrateur dans ses propres chansons ?",
      choix: ["Le nom d'un ami", "Le nom d'une femme", "Le nom du fqih", "Le nom d'un lieu"],
      reponseCorrecte: 1,
      explication: "Il compose son chant en y intégrant le nom d'une femme.",
    },
    {
      id: "c12-q8",
      question: "Qui envoie le petit garçon qui vient s'informer de la santé de Sidi Mohammed ?",
      choix: ["Le fqih", "Driss El Aouad", "Lalla Aïcha", "La Chouafa"],
      reponseCorrecte: 0,
      explication: "Le fqih envoie un élève prendre des nouvelles de Sidi Mohammed.",
    },
    {
      id: "c12-q9",
      question: "Que répond Lalla Zoubida au sujet de la santé de son fils ?",
      choix: [
        "Qu'il est complètement guéri",
        "Qu'il va mieux mais ne peut pas encore aller au Msid",
        "Qu'il va plus mal",
        "Qu'elle ne sait pas",
      ],
      reponseCorrecte: 1,
      explication: "Elle explique qu'il va mieux, sans être encore assez rétabli pour retourner au Msid.",
    },
    {
      id: "c12-q10",
      question: "Comment réagit Sidi Mohammed en apprenant qu'il doit bientôt retourner au Msid ?",
      choix: ["Il en est ravi", "Pris de peur, il se cache derrière le lit", "Il reste indifférent", "Il part en courant dehors"],
      reponseCorrecte: 1,
      explication: "Cette réaction craintive met sa mère en colère.",
    },
    {
      id: "c12-q11",
      question: "Comment réagit sa mère face à cette attitude ?",
      choix: ["Elle se met en colère", "Elle rit", "Elle le console", "Elle ne réagit pas"],
      reponseCorrecte: 0,
      explication: "Lalla Zoubida se met en colère devant le comportement craintif de son fils.",
    },
    {
      id: "c12-q12",
      question: "Pourquoi Zineb ne peut-elle pas s'expliquer tout de suite en rentrant précipitamment ?",
      choix: ["Elle est blessée", "Elle est trop excitée par la nouvelle", "Elle a couru longtemps", "Elle a peur"],
      reponseCorrecte: 1,
      explication: "Son excitation l'empêche d'abord de raconter clairement ce qu'elle a vu.",
    },
    {
      id: "c12-q13",
      question: "De quoi Driss El Aouad et Maâlem Abdeslem s'entretiennent-ils en se retrouvant ?",
      choix: [
        "Du prix du blé",
        "De la séparation de Moulay Larbi et de sa deuxième épouse",
        "Du voyage de moisson",
        "De la santé de Sidi Mohammed",
      ],
      reponseCorrecte: 1,
      explication: "Les deux hommes discutent de cette séparation déjà évoquée au chapitre 8.",
    },
    {
      id: "c12-q14",
      question: "Qui, en plus de Lalla Zoubida et Sidi Mohammed, se réjouit du retour du père ?",
      choix: ["Personne d'autre", "Les voisines", "Uniquement le fqih", "Uniquement Driss El Aouad"],
      reponseCorrecte: 1,
      explication: "Les voisines partagent elles aussi la joie de ce retour chargé de provisions.",
    },
    {
      id: "c12-q15",
      question: "Quel est le thème principal de ce chapitre, selon la fiche de lecture ?",
      choix: ["Le retour et la réconciliation", "La peur de la mort", "Le commerce", "La religiosité populaire"],
      reponseCorrecte: 0,
      explication: "Le retour du père et les retrouvailles heureuses closent le roman sur ce thème.",
    },
  ],
};
